# Generated by Django 5.0.1 on 2024-02-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_rename_students_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.CharField(max_length=200),
        ),
    ]
