# Generated by Django 5.0.1 on 2024-02-04 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_alter_student_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
